--- # conditional
- hosts: all
  become: true
  connection: ssh
  tasks:
   - name: install apache server on debian
     command: apt-get -y install apache2
     when: ansible_os_family == 'Debian'
   - name: install apache server for redhat
     command: yum -y install httpd
     when: ansible_os_family == 'RedHat' 
